version: '3'

services:
  neo4j:
    image: neo4j:4.4
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 10s
      timeout: 10s
      retries: 5

  cardio-kg:
    build: .
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - PUBMED_EMAIL=${PUBMED_EMAIL}
      - PUBMED_API_KEY=${PUBMED_API_KEY}
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
    restart: on-failure

volumes:
  neo4j_data:
  neo4j_logs: 